"use client";

import { useState } from "react";
import { LockKeyhole, UserRoundPlus, X } from "lucide-react";
import type { LearningProfile } from "@/lib/learning-profiles-api";
import { useLearningProfile } from "./LearningProfileContext";

export function ProfileUnlockDialog({ profile, createMode = false, onClose }: { profile?: LearningProfile; createMode?: boolean; onClose: () => void }) {
  const { create, unlock } = useLearningProfile(); const [name, setName] = useState(""); const [pin, setPin] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { if (createMode) { const created = await create(name, pin); await unlock(created.id, pin); } else if (profile) await unlock(profile.id, pin); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败，请重试"); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-[var(--overlay)]/70 px-4 backdrop-blur-sm" role="dialog" aria-modal="true"><form onSubmit={submit} className="w-full max-w-sm rounded-3xl border border-[var(--border)] bg-[var(--card)] p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between gap-4"><div className="flex gap-3"><span className="rounded-2xl bg-[var(--primary)]/10 p-3 text-[var(--primary)]">{createMode ? <UserRoundPlus size={22} /> : <LockKeyhole size={22} />}</span><div><h2 className="font-semibold text-[var(--foreground)]">{createMode ? "新建学习档案" : `解锁 ${profile?.name ?? "学习档案"}`}</h2><p className="mt-1 text-xs leading-5 text-[var(--muted-foreground)]">同一账号可供多人使用，每个人的聊天、记忆和练习相互独立。</p></div></div><button type="button" onClick={onClose} className="rounded-lg p-1 text-[var(--muted-foreground)] hover:bg-[var(--muted)]"><X size={18} /></button></div>{createMode && <label className="mb-4 block text-sm text-[var(--foreground)]">档案名称<input autoFocus value={name} onChange={(e) => setName(e.target.value)} maxLength={40} placeholder="例如：小明" className="mt-2 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2.5 outline-none focus:ring-2 focus:ring-[var(--primary)]/30" /></label>}<label className="block text-sm text-[var(--foreground)]">数字 PIN<input autoFocus={!createMode} value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, "").slice(0, 12))} inputMode="numeric" type="password" minLength={4} required placeholder="4–12 位数字" className="mt-2 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2.5 tracking-[0.25em] outline-none focus:ring-2 focus:ring-[var(--primary)]/30" /></label>{error && <p className="mt-3 rounded-xl bg-red-500/10 px-3 py-2 text-sm text-red-600">{error}</p>}<button disabled={busy || pin.length < 4 || (createMode && !name.trim())} className="mt-5 w-full rounded-xl bg-[var(--primary)] px-4 py-2.5 font-medium text-[var(--primary-foreground)] transition hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-50">{busy ? "处理中…" : createMode ? "创建并进入" : "进入学习"}</button></form></div>;
}
