"use client";

import { useState } from "react";
import { ChevronDown, LockKeyhole, Plus, UserRound } from "lucide-react";
import type { LearningProfile } from "@/lib/learning-profiles-api";
import { useLearningProfile } from "./LearningProfileContext";
import { ProfileUnlockDialog } from "./ProfileUnlockDialog";

export function ProfileSwitcher({ collapsed = false }: { collapsed?: boolean }) {
  const { loading, profiles, active, lock } = useLearningProfile(); const [open, setOpen] = useState(false); const [target, setTarget] = useState<LearningProfile | null>(null); const [creating, setCreating] = useState(false);
  if (loading) return <div className={collapsed ? "mx-auto h-9 w-9 animate-pulse rounded-xl bg-[var(--muted)]" : "mx-2 h-11 animate-pulse rounded-xl bg-[var(--muted)]"} />;
  const choose = async (profile: LearningProfile) => { setOpen(false); if (active?.id === profile.id) return; if (active) await lock(); setTarget(profile); };
  return <><div className="relative mb-1"><button onClick={() => setOpen((value) => !value)} title={collapsed ? active?.name ?? "选择学习档案" : undefined} className={collapsed ? "mx-auto flex h-9 w-9 items-center justify-center rounded-xl border border-[var(--border)] bg-[var(--card)] text-[var(--foreground)]" : "mx-1 flex w-[calc(100%-0.5rem)] items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--card)] px-2.5 py-2 text-left shadow-sm transition hover:border-[var(--primary)]/40"}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500 to-violet-500 text-xs font-semibold text-white">{active?.name?.slice(0, 1) ?? <UserRound size={15} />}</span>{!collapsed && <><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium text-[var(--foreground)]">{active?.name ?? "选择学习档案"}</span><span className="block text-[10px] text-[var(--muted-foreground)]">{active ? "记忆区域已解锁" : "聊天与练习已锁定"}</span></span><ChevronDown size={14} className={open ? "rotate-180 transition" : "transition"} /></>}</button>{open && <div className={collapsed ? "absolute bottom-0 left-12 z-50 w-56 rounded-2xl border border-[var(--border)] bg-[var(--popover)] p-2 shadow-xl" : "absolute bottom-full left-1 z-50 mb-2 w-[calc(100%-0.5rem)] rounded-2xl border border-[var(--border)] bg-[var(--popover)] p-2 shadow-xl"}><p className="px-2 pb-1 text-[10px] uppercase tracking-wider text-[var(--muted-foreground)]">谁在学习</p>{profiles.map((profile) => <button key={profile.id} onClick={() => void choose(profile)} className="flex w-full items-center gap-2 rounded-xl px-2 py-2 text-left hover:bg-[var(--muted)]"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[var(--accent)] text-xs">{profile.name.slice(0, 1)}</span><span className="flex-1 truncate text-sm text-[var(--foreground)]">{profile.name}</span>{active?.id === profile.id ? <span className="h-2 w-2 rounded-full bg-emerald-500" /> : <LockKeyhole size={12} className="text-[var(--muted-foreground)]" />}</button>)}<button onClick={() => { setOpen(false); setCreating(true); }} className="mt-1 flex w-full items-center gap-2 rounded-xl border border-dashed border-[var(--border)] px-2 py-2 text-sm text-[var(--muted-foreground)] hover:border-[var(--primary)]/50 hover:text-[var(--foreground)]"><Plus size={15} /> 新建学习档案</button>{active && <button onClick={() => { setOpen(false); void lock(); }} className="mt-1 w-full rounded-xl px-2 py-2 text-left text-xs text-[var(--muted-foreground)] hover:bg-[var(--muted)]">锁定当前档案</button>}</div>}</div>{target && <ProfileUnlockDialog profile={target} onClose={() => setTarget(null)} />}{creating && <ProfileUnlockDialog createMode onClose={() => setCreating(false)} />}</>;
}
